<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>cake</string>
		<string>funnelcake</string>
	</array>
	<key>name</key>
	<string>FunnelCake</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b\d+\b</string>
			<key>name</key>
			<string>constant.numeric.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btrue\b</string>
			<key>name</key>
			<string>constant.language.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bfalse\b</string>
			<key>name</key>
			<string>constant.language.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^//.*</string>
			<key>name</key>
			<string>comment.line.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>".*?"</string>
			<key>name</key>
			<string>string.quoted.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&gt;=</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=&lt;</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!=</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;&amp;</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\!</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\+</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&gt;</string>
			<key>name</key>
			<string>keyword.operator.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>=</string>
			<key>name</key>
			<string>constant.language.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;</string>
			<key>name</key>
			<string>constant.language.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bmin\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bmax\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btopX\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\blatest\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsum\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bcount\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bavg\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bsumActiveUser\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bcountActiveUser\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bavgActiveUser\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bnumResponseActiveUser\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btoLowerCase\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\btoUpperCase\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bisEmpty\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\binList\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bcontains\b</string>
			<key>name</key>
			<string>support.function.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bMIN\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bMAX\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bALL\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bTIMEONLY\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\REFRESHRATE\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bFILTER\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bGROUP\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bSPLIT\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bTRANSFORM\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bMERGE\b</string>
			<key>name</key>
			<string>keyword.control.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bAGG\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bLEADERBOARD\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bPARSE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bREMOVE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bWHERE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bBY\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bTOP\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bAS\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bIN\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bCONTAINS\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bWITH\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bUSING\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bINTO\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bUNIQUE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bUSECASE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bIGNORECASE\b</string>
			<key>name</key>
			<string>keyword.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bINPUT\b</string>
			<key>name</key>
			<string>support.type.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bOUTPUT\b</string>
			<key>name</key>
			<string>support.type.funnelcake</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\bFC\b</string>
			<key>name</key>
			<string>support.type.funnelcake</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.funnelcake</string>
	<key>uuid</key>
	<string>386489ff-0c0b-4a98-8dbb-cb18766cf961</string>
</dict>
</plist>
